#!/usr/bin/env python3
# calibrate_driver.py — drive calibrate.ino's serial walkthrough and write config.h.
#
# The calibrate sketch prints a prompt per side ("... press Enter"), waits for a
# newline on serial, captures the accelerometer vector, and at the end emits a
# config.h block between BEGIN/END markers. This script bridges that session to
# your terminal (device output -> stdout, your Enter -> device) and captures the
# emitted block into firmware/config.h — no copy-paste.
#
# Usage: calibrate_driver.py <port> <config_path>
import sys
import time
import select
import serial  # pyserial (installed in the repo .venv)

BEGIN = "----- BEGIN config.h -----"
END = "----- END config.h -----"


def open_port(port, retries=50, delay=0.2):
    # After flashing, the XIAO re-enumerates over native USB, so the port can be
    # briefly absent. Retry the open for ~10s before giving up.
    last = None
    for _ in range(retries):
        try:
            return serial.Serial(port, 115200, timeout=0.1)
        except (serial.SerialException, OSError) as e:
            last = e
            time.sleep(delay)
    raise last


def main():
    if len(sys.argv) != 3:
        print("usage: calibrate_driver.py <port> <config_path>", file=sys.stderr)
        return 2
    port, config_path = sys.argv[1], sys.argv[2]

    ser = open_port(port)
    # Handshake: the sketch blocks until it receives a byte before printing anything,
    # so nothing is lost to the C6's always-on USB serial. Send one newline to start.
    ser.write(b"\n")
    ser.flush()

    rx = ""            # rolling buffer, split on newlines for marker detection
    captured = []      # lines between the markers (exclusive)
    capturing = False

    while True:
        ready, _, _ = select.select([ser.fileno(), sys.stdin.fileno()], [], [])

        if ser.fileno() in ready:
            data = ser.read(4096)
            if data:
                text = data.decode("utf-8", "replace")
                sys.stdout.write(text)   # echo device output live
                sys.stdout.flush()
                rx += text
                while "\n" in rx:
                    line, rx = rx.split("\n", 1)
                    line = line.rstrip("\r")
                    if line.strip() == END:
                        _write_config(config_path, captured)
                        ser.close()
                        return 0
                    if capturing:
                        captured.append(line)
                    elif line.strip() == BEGIN:
                        capturing = True

        if sys.stdin.fileno() in ready:
            # A blank Enter is all the sketch needs; forward whatever the user typed.
            user = sys.stdin.readline()
            if user == "":            # EOF (Ctrl-D) — bail without writing
                print("\n>> aborted (EOF) — config.h not written", file=sys.stderr)
                ser.close()
                return 1
            ser.write(b"\n")
            ser.flush()


HEADER = (
    "// config.h — orientation calibration for the DND cube.\n"
    "//\n"
    "// GENERATED by `./upload.sh calibrate`. Re-run that to regenerate; don't hand-edit.\n"
    "// Each row is the accelerometer reading (in g) when that side faces UP.\n"
)


def _write_config(path, lines):
    body = "\n".join(lines).rstrip("\n") + "\n"
    with open(path, "w") as f:
        f.write(HEADER + body)
    print(f"\n>> Wrote {path}", file=sys.stderr)


if __name__ == "__main__":
    sys.exit(main())
