// config.h — orientation calibration for the DND cube.
//
// GENERATED by `./upload.sh calibrate`. Re-run that to regenerate; don't hand-edit.
// Each row is the accelerometer reading (in g) when that side faces UP.
#pragma once
#include <DndBox.h>

static const SideRef SIDES[] = {
  { "RED", -0.9647f, -0.0153f, 0.1765f, PIN_LED_RED },
  { "GREEN", 1.0375f, 0.0770f, -0.3267f, PIN_LED_GREEN },
  { "YELLOW", 0.2797f, 0.0132f, 0.8917f, PIN_LED_YELLOW },
  { "BLUE", -0.2234f, 0.0654f, -1.0351f, PIN_LED_BLUE },
  { "TOP", 0.0292f, 1.0652f, -0.0260f, -1 },
  { "BOTTOM", 0.0715f, -1.0069f, -0.1805f, -1 },
};
static const int NUM_SIDES = sizeof(SIDES) / sizeof(SIDES[0]);
